import { Sound } from '@/types';

export const SOUNDS: Sound[] = [
  // Radio Commands
  {
    id: 'cover-me',
    name: 'Cover Me',
    file: '/audio/ct_coverme.wav',
    category: 'radio',
    label: 'Cover Me!',
  },
  {
    id: 'need-backup',
    name: 'Need Backup',
    file: '/audio/ct_backup.wav',
    category: 'radio',
    label: 'Need Backup',
  },
  {
    id: 'hold-position',
    name: 'Hold Position',
    file: '/audio/position.wav',
    category: 'radio',
    label: 'Hold This Position',
  },
  {
    id: 'regroup',
    name: 'Regroup',
    file: '/audio/regroup.wav',
    category: 'radio',
    label: 'Regroup Team',
  },
  {
    id: 'follow-me',
    name: 'Follow Me',
    file: '/audio/followme.wav',
    category: 'radio',
    label: 'Follow Me',
  },
  {
    id: 'taking-fire',
    name: 'Taking Fire',
    file: '/audio/ct_imhit.wav',
    category: 'radio',
    label: 'Taking Fire, Need Assistance!',
  },
  {
    id: 'point',
    name: 'You Take The Point',
    file: '/audio/ct_point.wav',
    category: 'radio',
    label: 'You Take The Point',
  },
  {
    id: 'stick-together',
    name: 'Stick Together',
    file: '/audio/sticktog.wav',
    category: 'radio',
    label: 'Stick Together Team',
  },
  {
    id: 'meet-me',
    name: 'Meet Me Here',
    file: '/audio/meetme.wav',
    category: 'radio',
    label: 'Meet Me At This Spot',
  },

  // Commands
  {
    id: 'go-go-go',
    name: 'Go Go Go',
    file: '/audio/com_go.wav',
    category: 'commands',
    label: 'Go Go Go!',
  },
  {
    id: 'follow-commander',
    name: 'Follow Commander',
    file: '/audio/com_followcom.wav',
    category: 'commands',
    label: 'Team, Follow Me',
  },
  {
    id: 'report-in',
    name: 'Report In',
    file: '/audio/com_reportin.wav',
    category: 'commands',
    label: 'Report In, Team',
  },
  {
    id: 'get-in-position',
    name: 'Get In Position',
    file: '/audio/com_getinpos.wav',
    category: 'commands',
    label: 'Get In Position',
  },
  {
    id: 'storm-front',
    name: 'Storm Front',
    file: '/audio/stormfront.wav',
    category: 'commands',
    label: 'Storm The Front!',
  },
  {
    id: 'fallback',
    name: 'Fall Back',
    file: '/audio/fallback.wav',
    category: 'commands',
    label: 'Fall Back!',
  },
  {
    id: 'take-point',
    name: 'Take Point',
    file: '/audio/takepoint.wav',
    category: 'commands',
    label: 'Take The Point',
  },
  {
    id: 'hold-position-cmd',
    name: 'Hold Position',
    file: '/audio/position.wav',
    category: 'commands',
    label: 'Hold This Position!',
  },
  {
    id: 'move-out',
    name: 'Move Out',
    file: '/audio/moveout.wav',
    category: 'commands',
    label: 'Move Out!',
  },
  {
    id: 'flank-them',
    name: 'Flank Them',
    file: '/audio/flankthem.wav',
    category: 'commands',
    label: 'Flank Them!',
  },
  {
    id: 'circle-back',
    name: 'Circle Back',
    file: '/audio/circleback.wav',
    category: 'commands',
    label: 'Circle Back',
  },
  {
    id: 'lets-go',
    name: "Let's Go",
    file: '/audio/letsgo.wav',
    category: 'commands',
    label: "Let's Go!",
  },
  { id: 'go', name: 'Go!', file: '/audio/go.wav', category: 'commands', label: 'Go!' },
  {
    id: 'get-out',
    name: 'Get Out',
    file: '/audio/getout.wav',
    category: 'commands',
    label: 'Get Out Of There!',
  },

  // Responses
  {
    id: 'roger',
    name: 'Roger',
    file: '/audio/roger.wav',
    category: 'responses',
    label: 'Roger That',
  },
  {
    id: 'affirmative',
    name: 'Affirmative',
    file: '/audio/ct_affirm.wav',
    category: 'responses',
    label: 'Affirmative',
  },
  {
    id: 'negative',
    name: 'Negative',
    file: '/audio/negative.wav',
    category: 'responses',
    label: 'Negative',
  },
  {
    id: 'reporting-in',
    name: 'Reporting In',
    file: '/audio/ct_reportingin.wav',
    category: 'responses',
    label: 'Reporting In',
  },
  {
    id: 'in-position',
    name: 'In Position',
    file: '/audio/ct_inpos.wav',
    category: 'responses',
    label: 'In Position',
  },
  {
    id: 'sector-clear',
    name: 'Sector Clear',
    file: '/audio/clear.wav',
    category: 'responses',
    label: 'Sector Clear',
  },

  // Events
  {
    id: 'enemy-spotted',
    name: 'Enemy Spotted',
    file: '/audio/ct_enemys.wav',
    category: 'events',
    label: 'Enemy Spotted',
  },
  {
    id: 'enemy-down',
    name: 'Enemy Down',
    file: '/audio/enemydown.wav',
    category: 'events',
    label: 'Enemy Down',
  },
  {
    id: 'fire-in-hole',
    name: 'Fire In Hole',
    file: '/audio/ct_fireinhole.wav',
    category: 'events',
    label: 'Fire In The Hole!',
  },
  {
    id: 'bomb-planted',
    name: 'Bomb Planted',
    file: '/audio/bombpl.wav',
    category: 'events',
    label: 'Bomb Has Been Planted',
  },
  {
    id: 'bomb-defused',
    name: 'Bomb Defused',
    file: '/audio/bombdef.wav',
    category: 'events',
    label: 'Bomb Has Been Defused',
  },
  {
    id: 'ct-win',
    name: 'CT Win',
    file: '/audio/ctwin.wav',
    category: 'events',
    label: 'Counter-Terrorists Win',
  },
  {
    id: 'ter-win',
    name: 'T Win',
    file: '/audio/terwin.wav',
    category: 'events',
    label: 'Terrorists Win',
  },
  {
    id: 'round-draw',
    name: 'Round Draw',
    file: '/audio/rounddraw.wav',
    category: 'events',
    label: 'Round Draw',
  },
  { id: 'blow', name: 'Blow', file: '/audio/blow.wav', category: 'events', label: 'Blow!' },
  {
    id: 'eliminated',
    name: 'Eliminated',
    file: '/audio/elim.wav',
    category: 'events',
    label: 'Target Eliminated',
  },
  {
    id: 'teammate-down',
    name: 'Teammate Down',
    file: '/audio/matedown.wav',
    category: 'events',
    label: 'Teammate Down',
  },
  {
    id: 'hostage-down',
    name: 'Hostage Down',
    file: '/audio/hosdown.wav',
    category: 'events',
    label: 'Hostage Down',
  },
  {
    id: 'hostage-rescued',
    name: 'Hostage Rescued',
    file: '/audio/rescued.wav',
    category: 'events',
    label: 'Hostage Rescued',
  },
  { id: 'vip', name: 'VIP', file: '/audio/vip.wav', category: 'events', label: 'VIP' },
  {
    id: 'fire-assistance',
    name: 'Fire Assistance',
    file: '/audio/fireassis.wav',
    category: 'events',
    label: 'Requesting Fire Assistance',
  },
  {
    id: 'hit-assistance',
    name: 'Hit Assistance',
    file: '/audio/hitassist.wav',
    category: 'events',
    label: 'Taking Heavy Fire!',
  },
  {
    id: 'lock-and-load',
    name: 'Lock And Load',
    file: '/audio/locknload.wav',
    category: 'events',
    label: 'Lock And Load!',
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  radio: 'Radio Commands',
  commands: 'Team Commands',
  responses: 'Responses',
  events: 'Events',
};
