import { Sound } from '@/types';

export const SOUNDS: Sound[] = [
  // 🔥 Top Sons
  {
    id: 'fire-in-hole',
    name: 'Fire In Hole',
    file: 'ct_fireinhole.wav',
    category: 'top',
    label: '💣 ÇA VA PÉTER !',
  },
  {
    id: 'ct-win',
    name: 'CT Win',
    file: 'ctwin.wav',
    category: 'top',
    label: '🏆 Victoire Anti-Terroristes',
  },
  {
    id: 'ter-win',
    name: 'T Win',
    file: 'terwin.wav',
    category: 'top',
    label: '💀 Victoire Terroristes',
  },
  {
    id: 'blow',
    name: 'Blow',
    file: 'blow.wav',
    category: 'top',
    label: "🚨 Sortez d'ici ça va sauter !",
  },

  // Commandes Radio
  {
    id: 'cover-me',
    name: 'Cover Me',
    file: 'ct_coverme.wav',
    category: 'radio',
    label: '🛡️ Couvrez-moi !',
  },
  {
    id: 'need-backup',
    name: 'Need Backup',
    file: 'ct_backup.wav',
    category: 'radio',
    label: "🚨 J'ai besoin de soutien",
  },
  {
    id: 'hold-position',
    name: 'Hold Position',
    file: 'position.wav',
    category: 'radio',
    label: '✋ Tenez la position',
  },
  {
    id: 'regroup',
    name: 'Regroup',
    file: 'regroup.wav',
    category: 'radio',
    label: '🔄 Regroupez-vous',
  },
  {
    id: 'follow-me',
    name: 'Follow Me',
    file: 'followme.wav',
    category: 'radio',
    label: '👉 Suivez-moi',
  },
  {
    id: 'taking-fire',
    name: 'Taking Fire',
    file: 'ct_imhit.wav',
    category: 'radio',
    label: '💥 Je suis touché',
  },
  {
    id: 'point',
    name: 'You Take The Point',
    file: 'ct_point.wav',
    category: 'radio',
    label: '🎯 Je prends le point',
  },
  {
    id: 'stick-together',
    name: 'Stick Together',
    file: 'sticktog.wav',
    category: 'radio',
    label: '🤝 Restez groupés',
  },
  {
    id: 'meet-me',
    name: 'Meet Me Here',
    file: 'meetme.wav',
    category: 'radio',
    label: '📍 Tous au point de RDV',
  },

  // Ordres Tactiques
  {
    id: 'go-go-go',
    name: 'Go Go Go',
    file: 'com_go.wav',
    category: 'commands',
    label: '⚡ Go Go Go !',
  },
  {
    id: 'follow-commander',
    name: 'Follow Commander',
    file: 'com_followcom.wav',
    category: 'commands',
    label: '👮 Ok, suivez mes ordres',
  },
  {
    id: 'report-in',
    name: 'Report In',
    file: 'com_reportin.wav',
    category: 'commands',
    label: '📢 Au rapport',
  },
  {
    id: 'get-in-position',
    name: 'Get In Position',
    file: 'com_getinpos.wav',
    category: 'commands',
    label: '🎯 Prenez position et attendez mon Go !',
  },
  {
    id: 'storm-front',
    name: 'Storm Front',
    file: 'stormfront.wav',
    category: 'commands',
    label: "⚔️ Lancez l'assaut !",
  },
  {
    id: 'fallback',
    name: 'Fall Back',
    file: 'fallback.wav',
    category: 'commands',
    label: '↩️ Groupe, rassemblement !',
  },
  {
    id: 'take-point',
    name: 'Take Point',
    file: 'takepoint.wav',
    category: 'commands',
    label: '🔝 Vous prenez le point',
  },
  {
    id: 'move-out',
    name: 'Move Out',
    file: 'moveout.wav',
    category: 'commands',
    label: "🏃 Allez c'est parti",
  },
  {
    id: 'flank-them',
    name: 'Flank Them',
    file: 'flankthem.wav',
    category: 'commands',
    label: '↪️ Contournez-les !',
  },
  {
    id: 'circle-back',
    name: 'Circle Back',
    file: 'circleback.wav',
    category: 'commands',
    label: '🔄 Prenez les à revers',
  },
  {
    id: 'lets-go',
    name: "Let's Go",
    file: 'letsgo.wav',
    category: 'commands',
    label: '🚀 Ok, on y va !',
  },
  {
    id: 'get-out',
    name: 'Get Out',
    file: 'getout.wav',
    category: 'commands',
    label: '🏃‍♂️ A tout le groupe on sort de là !',
  },

  // Réponses
  {
    id: 'roger',
    name: 'Roger',
    file: 'roger.wav',
    category: 'responses',
    label: '✅ Bien compris',
  },
  {
    id: 'affirmative',
    name: 'Affirmative',
    file: 'ct_affirm.wav',
    category: 'responses',
    label: '👍 Affirmatif',
  },
  {
    id: 'negative',
    name: 'Negative',
    file: 'negative.wav',
    category: 'responses',
    label: '❌ Négatif',
  },
  {
    id: 'reporting-in',
    name: 'Reporting In',
    file: 'ct_reportingin.wav',
    category: 'responses',
    label: '📻 Au rapport',
  },
  {
    id: 'in-position',
    name: 'In Position',
    file: 'ct_inpos.wav',
    category: 'responses',
    label: '✔️ Je suis en position',
  },
  {
    id: 'sector-clear',
    name: 'Sector Clear',
    file: 'clear.wav',
    category: 'responses',
    label: '🟢 Zone sécurisée',
  },

  // Événements
  {
    id: 'enemy-spotted',
    name: 'Enemy Spotted',
    file: 'ct_enemys.wav',
    category: 'events',
    label: '👁️ Ennemi repéré',
  },
  {
    id: 'enemy-down',
    name: 'Enemy Down',
    file: 'enemydown.wav',
    category: 'events',
    label: '☠️ Ennemi à terre',
  },
  {
    id: 'bomb-planted',
    name: 'Bomb Planted',
    file: 'bombpl.wav',
    category: 'events',
    label: '💥 Bombe en place',
  },
  {
    id: 'bomb-defused',
    name: 'Bomb Defused',
    file: 'bombdef.wav',
    category: 'events',
    label: '✂️ La bombe a été désamorcée',
  },
  {
    id: 'round-draw',
    name: 'Round Draw',
    file: 'rounddraw.wav',
    category: 'events',
    label: '🤝 Match nul',
  },
  {
    id: 'eliminated',
    name: 'Eliminated',
    file: 'elim.wav',
    category: 'events',
    label: '⚰️ Groupe infiltré et éliminé',
  },
  {
    id: 'teammate-down',
    name: 'Teammate Down',
    file: 'matedown.wav',
    category: 'events',
    label: '🩹 Équipier à terre',
  },
  {
    id: 'hostage-down',
    name: 'Hostage Down',
    file: 'hosdown.wav',
    category: 'events',
    label: '😵 Otage à terre',
  },
  {
    id: 'hostage-rescued',
    name: 'Hostage Rescued',
    file: 'rescued.wav',
    category: 'events',
    label: '🆓 Otage libéré',
  },
  {
    id: 'vip',
    name: 'VIP',
    file: 'vip.wav',
    category: 'events',
    label: '👤 Protégez le VIP',
  },
  {
    id: 'fire-assistance',
    name: 'Fire Assistance',
    file: 'fireassis.wav',
    category: 'events',
    label: '🔥 Demande de couverture',
  },
  {
    id: 'hit-assistance',
    name: 'Hit Assistance',
    file: 'hitassist.wav',
    category: 'events',
    label: "🆘 Je suis touché, j'ai besoin d'aide",
  },
  {
    id: 'lock-and-load',
    name: 'Lock And Load',
    file: 'locknload.wav',
    category: 'events',
    label: '🔫 Tenez vous prêts !',
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  top: '🔥 Les Plus Mythiques',
  radio: '📻 Commandes Radio',
  commands: '⚔️ Ordres Tactiques',
  responses: '💬 Réponses',
  events: '🎯 Événements',
};
